FROM golang:1.14-alpine as build

WORKDIR apps/iotube-relayer

RUN apk add --no-cache make gcc musl-dev linux-headers git

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN mkdir -p $GOPATH/pkg/linux_amd64/github.com/iotexproject/ && \
    make clean build-relayer

FROM alpine:latest

RUN apk add --no-cache ca-certificates
RUN mkdir -p /etc/iotube/
COPY --from=build /go/apps/iotube-relayer/bin/relayer /usr/local/bin/relayer

CMD [ "relayer" ]
