version: '2'

services:
  database:
    container_name: witness-db
    image: mysql:8
    restart: always
    ports:
      - 13306:3306
    volumes:
      - $IOTEX_WITNESS/data/mysql:/var/lib/mysql:rw
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  iotex-witness:
    container_name: iotex-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-iotex.yaml:/etc/iotube-witness/witness-config-iotex.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-iotex.secret.yaml:/etc/iotube-witness/witness-config-iotex.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-iotex.yaml -secret=/etc/iotube-witness/witness-config-iotex.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

  ethereum-witness:
    container_name: ethereum-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-ethereum.yaml:/etc/iotube-witness/witness-config-ethereum.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-ethereum.secret.yaml:/etc/iotube-witness/witness-config-ethereum.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-ethereum.yaml -secret=/etc/iotube-witness/witness-config-ethereum.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

  iotex-testnet-witness:
    container_name: iotex-testnet-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-iotex-testnet.yaml:/etc/iotube-witness/witness-config-iotex-testnet.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-iotex-testnet.secret.yaml:/etc/iotube-witness/witness-config-iotex-testnet.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-iotex-testnet.yaml -secret=/etc/iotube-witness/witness-config-iotex-testnet.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

  sepolia-witness:
    container_name: sepolia-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-sepolia.yaml:/etc/iotube-witness/witness-config-sepolia.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-sepolia.secret.yaml:/etc/iotube-witness/witness-config-sepolia.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-sepolia.yaml -secret=/etc/iotube-witness/witness-config-sepolia.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

#  heco-witness:
#    container_name: heco-witness
#    image: witness:latest
#    restart: on-failure
#    volumes:
#      - $IOTEX_WITNESS/etc/witness-config-heco.yaml:/etc/iotube-witness/witness-config-heco.yaml:ro
#      - $IOTEX_WITNESS/etc/witness-config-heco.secret.yaml:/etc/iotube-witness/witness-config-heco.secret.yaml:ro
#    network_mode: host
#    command: witness -config=/etc/iotube-witness/witness-config-heco.yaml -secret=/etc/iotube-witness/witness-config-heco.secret.yaml
#    environment:
#      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
#      RELAYER_URL: ${RELAYER_URL}

#  polis-witness:
#    container_name: polis-witness
#    image: witness:latest
#    restart: on-failure
#    volumes:
#      - $IOTEX_WITNESS/etc/witness-config-polis.yaml:/etc/iotube-witness/witness-config-polis.yaml:ro
#      - $IOTEX_WITNESS/etc/witness-config-polis.secret.yaml:/etc/iotube-witness/witness-config-polis.secret.yaml:ro
#    network_mode: host
#    command: witness -config=/etc/iotube-witness/witness-config-polis.yaml -secret=/etc/iotube-witness/witness-config-polis.secret.yaml
#    environment:
#      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
#      RELAYER_URL: ${RELAYER_URL}

  bsc-witness:
    container_name: bsc-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-bsc.yaml:/etc/iotube-witness/witness-config-bsc.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-bsc.secret.yaml:/etc/iotube-witness/witness-config-bsc.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-bsc.yaml -secret=/etc/iotube-witness/witness-config-bsc.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

  matic-witness:
    container_name: matic-witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-matic.yaml:/etc/iotube-witness/witness-config-matic.yaml:ro
      - $IOTEX_WITNESS/etc/witness-config-matic.secret.yaml:/etc/iotube-witness/witness-config-matic.secret.yaml:ro
    network_mode: host
    command: witness -config=/etc/iotube-witness/witness-config-matic.yaml -secret=/etc/iotube-witness/witness-config-matic.secret.yaml
    environment:
      WITNESS_PRIVATE_KEY: ${WITNESS_PRIVATE_KEY}
      RELAYER_URL: ${RELAYER_URL}

  cron:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - $IOTEX_WITNESS/etc/crontab:/var/spool/cron/crontabs/root
      - $IOTEX_WITNESS/etc/backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: witness

  backup:
    image: busybox
    volumes:
      - $IOTEX_WITNESS/data/backup:/backup
