chain: "iotex-testnet"
grpcPort: 9180
grpcProxyPort: 9181
interval: 10s
batchSize: 1000
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-testnet-to-sepolia"
    withPayload: true
    relayerURL: ":7100"
    cashierContractAddress: "io1u9lnzeyugt8qxpqq3jqlk7539njwsguq4j2hu2"
    validatorContractAddress: "0xfbaDFfe2B6c7D700eF74B130f4154dF3412eB0E6"
    startBlockHeight: 25608929
    transferTableName: "iotex_testnet_transfers"
    tokenPairs:
      # IOTX
      - token1: "0x4f8E54a8d05cb6e55F1713C01CA6f636F0eb30DD"
        token2: "0xC75A4F0125f98E6998C0b6c3036a32340E0f40A8"
      # WETH
      - token1: "0xB63feDD1F256dc81D9F45D21CF1Ed03971a9D9D3"
        token2: "0x4E11A2FB99fDCF1a4e7480B66d262eDD77a225A4"
      # USDT
      - token1: "0xa8CB715963e521B960D8c988155AD21eeD69827B"
        token2: "0x309489f1f90ce72d0bd9f391848cc9dfc2f22566"
