chain: "heco"
grpcPort: 9088
grpcProxyPort: 9089
interval: 1m
batchSize: 40
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "heco-to-iotex"
    relayerURL: ":7001"
    startBlockHeight: 2431000
    validatorContractAddress: "io10xr64as4krm5nufd5l2ddc43al6tl0smumkg7y"
    cashierContractAddress: "0xC8DC8dCDFd94f9Cb953f379a7aD8Da5fdC303F3E"
    transferTableName: "heco_transfers"
    tokenPairs:
