// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: services/explorer-service.proto

package services

import (
	types "github.com/iotexproject/ioTube/witness-service/grpc/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExplorerQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         int32                  `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Token         []byte                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Sender        []byte                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     []byte                 `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=services.Status" json:"status,omitempty"`
	Cashiers      [][]byte               `protobuf:"bytes,7,rep,name=cashiers,proto3" json:"cashiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplorerQueryRequest) Reset() {
	*x = ExplorerQueryRequest{}
	mi := &file_services_explorer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplorerQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplorerQueryRequest) ProtoMessage() {}

func (x *ExplorerQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_explorer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplorerQueryRequest.ProtoReflect.Descriptor instead.
func (*ExplorerQueryRequest) Descriptor() ([]byte, []int) {
	return file_services_explorer_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExplorerQueryRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *ExplorerQueryRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ExplorerQueryRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ExplorerQueryRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ExplorerQueryRequest) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *ExplorerQueryRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *ExplorerQueryRequest) GetCashiers() [][]byte {
	if x != nil {
		return x.Cashiers
	}
	return nil
}

type ExplorerQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*types.Transfer      `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Statuses      []*CheckResponse       `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplorerQueryResponse) Reset() {
	*x = ExplorerQueryResponse{}
	mi := &file_services_explorer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplorerQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplorerQueryResponse) ProtoMessage() {}

func (x *ExplorerQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_explorer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplorerQueryResponse.ProtoReflect.Descriptor instead.
func (*ExplorerQueryResponse) Descriptor() ([]byte, []int) {
	return file_services_explorer_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExplorerQueryResponse) GetTransfers() []*types.Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *ExplorerQueryResponse) GetStatuses() []*CheckResponse {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ExplorerQueryResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_services_explorer_service_proto protoreflect.FileDescriptor

const file_services_explorer_service_proto_rawDesc = "" +
	"\n" +
	"\x1fservices/explorer-service.proto\x12\bservices\x1a\x1cgoogle/api/annotations.proto\x1a\x13types/witness.proto\x1a\x1cservices/relay-service.proto\"\xd2\x01\n" +
	"\x14ExplorerQueryRequest\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x05R\x05first\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\fR\trecipient\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.services.StatusR\x06status\x12\x1a\n" +
	"\bcashiers\x18\a \x03(\fR\bcashiers\"\x91\x01\n" +
	"\x15ExplorerQueryResponse\x12-\n" +
	"\ttransfers\x18\x01 \x03(\v2\x0f.types.TransferR\ttransfers\x123\n" +
	"\bstatuses\x18\x02 \x03(\v2\x17.services.CheckResponseR\bstatuses\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count2m\n" +
	"\x0fExplorerService\x12Z\n" +
	"\x05Query\x12\x1e.services.ExplorerQueryRequest\x1a\x1f.services.ExplorerQueryResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/listB>Z<github.com/iotexproject/ioTube/witness-service/grpc/servicesb\x06proto3"

var (
	file_services_explorer_service_proto_rawDescOnce sync.Once
	file_services_explorer_service_proto_rawDescData []byte
)

func file_services_explorer_service_proto_rawDescGZIP() []byte {
	file_services_explorer_service_proto_rawDescOnce.Do(func() {
		file_services_explorer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_explorer_service_proto_rawDesc), len(file_services_explorer_service_proto_rawDesc)))
	})
	return file_services_explorer_service_proto_rawDescData
}

var file_services_explorer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_explorer_service_proto_goTypes = []any{
	(*ExplorerQueryRequest)(nil),  // 0: services.ExplorerQueryRequest
	(*ExplorerQueryResponse)(nil), // 1: services.ExplorerQueryResponse
	(Status)(0),                   // 2: services.Status
	(*types.Transfer)(nil),        // 3: types.Transfer
	(*CheckResponse)(nil),         // 4: services.CheckResponse
}
var file_services_explorer_service_proto_depIdxs = []int32{
	2, // 0: services.ExplorerQueryRequest.status:type_name -> services.Status
	3, // 1: services.ExplorerQueryResponse.transfers:type_name -> types.Transfer
	4, // 2: services.ExplorerQueryResponse.statuses:type_name -> services.CheckResponse
	0, // 3: services.ExplorerService.Query:input_type -> services.ExplorerQueryRequest
	1, // 4: services.ExplorerService.Query:output_type -> services.ExplorerQueryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_explorer_service_proto_init() }
func file_services_explorer_service_proto_init() {
	if File_services_explorer_service_proto != nil {
		return
	}
	file_services_relay_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_explorer_service_proto_rawDesc), len(file_services_explorer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_explorer_service_proto_goTypes,
		DependencyIndexes: file_services_explorer_service_proto_depIdxs,
		MessageInfos:      file_services_explorer_service_proto_msgTypes,
	}.Build()
	File_services_explorer_service_proto = out.File
	file_services_explorer_service_proto_goTypes = nil
	file_services_explorer_service_proto_depIdxs = nil
}
