// the grpc server is temporarily disabled in witness

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: services/witness-service.proto

package services

import (
	types "github.com/iotexproject/ioTube/witness-service/grpc/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_services_witness_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_witness_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_services_witness_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *types.Transfer        `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_services_witness_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_witness_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_services_witness_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetTransfer() *types.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heights       string                 `protobuf:"bytes,1,opt,name=heights,proto3" json:"heights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_services_witness_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_witness_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_services_witness_service_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetHeights() string {
	if x != nil {
		return x.Heights
	}
	return ""
}

var File_services_witness_service_proto protoreflect.FileDescriptor

const file_services_witness_service_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/witness-service.proto\x12\bservices\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13types/witness.proto\"\x1e\n" +
	"\fQueryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"<\n" +
	"\rQueryResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.types.TransferR\btransfer\"(\n" +
	"\fFetchRequest\x12\x18\n" +
	"\aheights\x18\x01 \x01(\tR\aheights2\xb2\x01\n" +
	"\x0eWitnessService\x12K\n" +
	"\x05Query\x12\x16.services.QueryRequest\x1a\x17.services.QueryResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/query\x12S\n" +
	"\x0eFetchByHeights\x12\x16.services.FetchRequest\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/fetchB>Z<github.com/iotexproject/ioTube/witness-service/grpc/servicesb\x06proto3"

var (
	file_services_witness_service_proto_rawDescOnce sync.Once
	file_services_witness_service_proto_rawDescData []byte
)

func file_services_witness_service_proto_rawDescGZIP() []byte {
	file_services_witness_service_proto_rawDescOnce.Do(func() {
		file_services_witness_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_witness_service_proto_rawDesc), len(file_services_witness_service_proto_rawDesc)))
	})
	return file_services_witness_service_proto_rawDescData
}

var file_services_witness_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_witness_service_proto_goTypes = []any{
	(*QueryRequest)(nil),   // 0: services.QueryRequest
	(*QueryResponse)(nil),  // 1: services.QueryResponse
	(*FetchRequest)(nil),   // 2: services.FetchRequest
	(*types.Transfer)(nil), // 3: types.Transfer
	(*emptypb.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_services_witness_service_proto_depIdxs = []int32{
	3, // 0: services.QueryResponse.transfer:type_name -> types.Transfer
	0, // 1: services.WitnessService.Query:input_type -> services.QueryRequest
	2, // 2: services.WitnessService.FetchByHeights:input_type -> services.FetchRequest
	1, // 3: services.WitnessService.Query:output_type -> services.QueryResponse
	4, // 4: services.WitnessService.FetchByHeights:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_witness_service_proto_init() }
func file_services_witness_service_proto_init() {
	if File_services_witness_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_witness_service_proto_rawDesc), len(file_services_witness_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_witness_service_proto_goTypes,
		DependencyIndexes: file_services_witness_service_proto_depIdxs,
		MessageInfos:      file_services_witness_service_proto_msgTypes,
	}.Build()
	File_services_witness_service_proto = out.File
	file_services_witness_service_proto_goTypes = nil
	file_services_witness_service_proto_depIdxs = nil
}
