// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: types/witness.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cashier       []byte                 `protobuf:"bytes,1,opt,name=cashier,proto3" json:"cashier,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Index         int64                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Sender        []byte                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     []byte                 `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Gas           uint64                 `protobuf:"varint,8,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      string                 `protobuf:"bytes,9,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Fee           string                 `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	TxSender      []byte                 `protobuf:"bytes,11,opt,name=txSender,proto3" json:"txSender,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,12,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	SourceTxHash  []byte                 `protobuf:"bytes,13,opt,name=sourceTxHash,proto3" json:"sourceTxHash,omitempty"`
	Payload       []byte                 `protobuf:"bytes,14,opt,name=payload,proto3" json:"payload,omitempty"`
	AtaOwner      []byte                 `protobuf:"bytes,15,opt,name=ataOwner,proto3" json:"ataOwner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_types_witness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_types_witness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_types_witness_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetCashier() []byte {
	if x != nil {
		return x.Cashier
	}
	return nil
}

func (x *Transfer) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Transfer) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Transfer) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transfer) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transfer) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transfer) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *Transfer) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transfer) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Transfer) GetTxSender() []byte {
	if x != nil {
		return x.TxSender
	}
	return nil
}

func (x *Transfer) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Transfer) GetSourceTxHash() []byte {
	if x != nil {
		return x.SourceTxHash
	}
	return nil
}

func (x *Transfer) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transfer) GetAtaOwner() []byte {
	if x != nil {
		return x.AtaOwner
	}
	return nil
}

type Witness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Witness) Reset() {
	*x = Witness{}
	mi := &file_types_witness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Witness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Witness) ProtoMessage() {}

func (x *Witness) ProtoReflect() protoreflect.Message {
	mi := &file_types_witness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Witness.ProtoReflect.Descriptor instead.
func (*Witness) Descriptor() ([]byte, []int) {
	return file_types_witness_proto_rawDescGZIP(), []int{1}
}

func (x *Witness) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *Witness) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Witness) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_types_witness_proto protoreflect.FileDescriptor

const file_types_witness_proto_rawDesc = "" +
	"\n" +
	"\x13types/witness.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\bTransfer\x12\x18\n" +
	"\acashier\x18\x01 \x01(\fR\acashier\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x05 \x01(\fR\trecipient\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03gas\x18\b \x01(\x04R\x03gas\x12\x1a\n" +
	"\bgasPrice\x18\t \x01(\tR\bgasPrice\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\tR\x03fee\x12\x1a\n" +
	"\btxSender\x18\v \x01(\fR\btxSender\x12 \n" +
	"\vblockHeight\x18\f \x01(\x04R\vblockHeight\x12\"\n" +
	"\fsourceTxHash\x18\r \x01(\fR\fsourceTxHash\x12\x18\n" +
	"\apayload\x18\x0e \x01(\fR\apayload\x12\x1a\n" +
	"\bataOwner\x18\x0f \x01(\fR\bataOwner\"n\n" +
	"\aWitness\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.types.TransferR\btransfer\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureB;Z9github.com/iotexproject/ioTube/witness-service/grpc/typesb\x06proto3"

var (
	file_types_witness_proto_rawDescOnce sync.Once
	file_types_witness_proto_rawDescData []byte
)

func file_types_witness_proto_rawDescGZIP() []byte {
	file_types_witness_proto_rawDescOnce.Do(func() {
		file_types_witness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_witness_proto_rawDesc), len(file_types_witness_proto_rawDesc)))
	})
	return file_types_witness_proto_rawDescData
}

var file_types_witness_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_witness_proto_goTypes = []any{
	(*Transfer)(nil),              // 0: types.Transfer
	(*Witness)(nil),               // 1: types.Witness
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_types_witness_proto_depIdxs = []int32{
	2, // 0: types.Transfer.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: types.Witness.transfer:type_name -> types.Transfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_witness_proto_init() }
func file_types_witness_proto_init() {
	if File_types_witness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_witness_proto_rawDesc), len(file_types_witness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_witness_proto_goTypes,
		DependencyIndexes: file_types_witness_proto_depIdxs,
		MessageInfos:      file_types_witness_proto_msgTypes,
	}.Build()
	File_types_witness_proto = out.File
	file_types_witness_proto_goTypes = nil
	file_types_witness_proto_depIdxs = nil
}
