// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: types/witnesseslist.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candidates struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WitnessManagerAddress []byte                 `protobuf:"bytes,1,opt,name=witnessManagerAddress,proto3" json:"witnessManagerAddress,omitempty"`
	Epoch                 uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WitnessesToAdd        [][]byte               `protobuf:"bytes,3,rep,name=witnessesToAdd,proto3" json:"witnessesToAdd,omitempty"`
	WitnessesToRemove     [][]byte               `protobuf:"bytes,4,rep,name=witnessesToRemove,proto3" json:"witnessesToRemove,omitempty"`
	Timestamp             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Candidates) Reset() {
	*x = Candidates{}
	mi := &file_types_witnesseslist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidates) ProtoMessage() {}

func (x *Candidates) ProtoReflect() protoreflect.Message {
	mi := &file_types_witnesseslist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidates.ProtoReflect.Descriptor instead.
func (*Candidates) Descriptor() ([]byte, []int) {
	return file_types_witnesseslist_proto_rawDescGZIP(), []int{0}
}

func (x *Candidates) GetWitnessManagerAddress() []byte {
	if x != nil {
		return x.WitnessManagerAddress
	}
	return nil
}

func (x *Candidates) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Candidates) GetWitnessesToAdd() [][]byte {
	if x != nil {
		return x.WitnessesToAdd
	}
	return nil
}

func (x *Candidates) GetWitnessesToRemove() [][]byte {
	if x != nil {
		return x.WitnessesToRemove
	}
	return nil
}

func (x *Candidates) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WitnessesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    *Candidates            `protobuf:"bytes,1,opt,name=candidates,proto3" json:"candidates,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessesList) Reset() {
	*x = WitnessesList{}
	mi := &file_types_witnesseslist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessesList) ProtoMessage() {}

func (x *WitnessesList) ProtoReflect() protoreflect.Message {
	mi := &file_types_witnesseslist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessesList.ProtoReflect.Descriptor instead.
func (*WitnessesList) Descriptor() ([]byte, []int) {
	return file_types_witnesseslist_proto_rawDescGZIP(), []int{1}
}

func (x *WitnessesList) GetCandidates() *Candidates {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *WitnessesList) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *WitnessesList) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_types_witnesseslist_proto protoreflect.FileDescriptor

const file_types_witnesseslist_proto_rawDesc = "" +
	"\n" +
	"\x19types/witnesseslist.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\n" +
	"Candidates\x124\n" +
	"\x15witnessManagerAddress\x18\x01 \x01(\fR\x15witnessManagerAddress\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12&\n" +
	"\x0ewitnessesToAdd\x18\x03 \x03(\fR\x0ewitnessesToAdd\x12,\n" +
	"\x11witnessesToRemove\x18\x04 \x03(\fR\x11witnessesToRemove\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"z\n" +
	"\rWitnessesList\x121\n" +
	"\n" +
	"candidates\x18\x01 \x01(\v2\x11.types.CandidatesR\n" +
	"candidates\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureB;Z9github.com/iotexproject/ioTube/witness-service/grpc/typesb\x06proto3"

var (
	file_types_witnesseslist_proto_rawDescOnce sync.Once
	file_types_witnesseslist_proto_rawDescData []byte
)

func file_types_witnesseslist_proto_rawDescGZIP() []byte {
	file_types_witnesseslist_proto_rawDescOnce.Do(func() {
		file_types_witnesseslist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_witnesseslist_proto_rawDesc), len(file_types_witnesseslist_proto_rawDesc)))
	})
	return file_types_witnesseslist_proto_rawDescData
}

var file_types_witnesseslist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_witnesseslist_proto_goTypes = []any{
	(*Candidates)(nil),            // 0: types.Candidates
	(*WitnessesList)(nil),         // 1: types.WitnessesList
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_types_witnesseslist_proto_depIdxs = []int32{
	2, // 0: types.Candidates.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: types.WitnessesList.candidates:type_name -> types.Candidates
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_witnesseslist_proto_init() }
func file_types_witnesseslist_proto_init() {
	if File_types_witnesseslist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_witnesseslist_proto_rawDesc), len(file_types_witnesseslist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_witnesseslist_proto_goTypes,
		DependencyIndexes: file_types_witnesseslist_proto_depIdxs,
		MessageInfos:      file_types_witnesseslist_proto_msgTypes,
	}.Build()
	File_types_witnesseslist_proto = out.File
	file_types_witnesseslist_proto_goTypes = nil
	file_types_witnesseslist_proto_depIdxs = nil
}
